# Used to be: google.com:phptest1
# http://goliardia-it.appspot.com/
application: goliardia-it
version: 112

runtime: php
api_version: 1

handlers:

- url: /redirect
  script: redirect.php

- url: /req
  script: request_headers.php

- url: /
  script: index.php

- url: /VERSION
  script: VERSION

- url: /hello
  script: hello.php

- url: /hello2
  script: hello2.php

- url: /login.php
  script: login.php

- url: /index.php.*
  script: mediawiki-1.21.0/index.php

- url: /mw-config/index.php
  script: mediawiki-1.21.0/mw-config/index.php

- url: /skins
  static_dir: mediawiki-1.21.0/skins
  application_readable: true

- url: /wiki/skins
  static_dir: mediawiki-1.21.0/skins
  application_readable: true

- url: /load.php
  script: mediawiki-1.21.0/load.php

- url: /resources
  static_dir: mediawiki-1.21.0/resources
  application_readable: true

- url: /user
  script: user.php
  login: required
  auth_fail_action: redirect

# images
- url: /static
  static_dir: static
# - url: /ferris/static
#   static_dir: ferris/static

# - url: /ferris/css
#   static_dir: ferris/static/css

# - url: /ferris/js
#   static_dir: ferris/static/js

# - url: /ferris/img
#   static_dir: ferris/static/img

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

# - url: /robots\.txt
#   static_files: app/static/robots.txt
#   upload: app/static/robots\.txt



## per ultimo
- url: /.*
  script: catchall.php