# Used to be: google.com:phptest1
# http://goliardia-it.appspot.com/
application: goliardia-it
version: 4

runtime: php
api_version: 1

handlers:
- url: /.*
  script: hello.php

- url: /redirect
  script: redirect.php

- url: /req
  script: request_headers.php

- url: /
  script: index.php

- url: /hello
  script: hello.php

- url: /hello2
  script: hello2.php

- url: /index.php.*
  script: mediawiki-1.21.0/index.php

- url: /mw-config/index.php
  script: mediawiki-1.21.0/mw-config/index.php

- url: /skins
  static_dir: mediawiki-1.21.0/skins
  application_readable: true

- url: /wiki/skins
  static_dir: mediawiki-1.21.0/skins
  application_readable: true

- url: /load.php
  script: mediawiki-1.21.0/load.php

- url: /resources
  static_dir: mediawiki-1.21.0/resources
  application_readable: true
